# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setConfig(object):
    def setupUi(self, setConfig):
        setConfig.setObjectName("setConfig")
        setConfig.resize(808, 566)
        self.outputdirButton = QtWidgets.QPushButton(setConfig)
        self.outputdirButton.setGeometry(QtCore.QRect(140, 160, 121, 41))
        self.outputdirButton.setObjectName("outputdirButton")
        self.inputdirButton = QtWidgets.QPushButton(setConfig)
        self.inputdirButton.setGeometry(QtCore.QRect(140, 80, 121, 41))
        self.inputdirButton.setObjectName("inputdirButton")
        self.inputdirEdit = QtWidgets.QTextEdit(setConfig)
        self.inputdirEdit.setGeometry(QtCore.QRect(300, 80, 281, 41))
        self.inputdirEdit.setObjectName("inputdirEdit")
        self.outputdirEdit = QtWidgets.QTextEdit(setConfig)
        self.outputdirEdit.setGeometry(QtCore.QRect(300, 160, 281, 41))
        self.outputdirEdit.setObjectName("outputdirEdit")
        self.okButton = QtWidgets.QPushButton(setConfig)
        self.okButton.setGeometry(QtCore.QRect(490, 490, 75, 23))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(setConfig)
        self.cancelButton.setGeometry(QtCore.QRect(570, 490, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.inputspinBox = QtWidgets.QSpinBox(setConfig)
        self.inputspinBox.setGeometry(QtCore.QRect(300, 320, 91, 41))
        self.inputspinBox.setObjectName("inputspinBox")
        self.outputspinBox = QtWidgets.QSpinBox(setConfig)
        self.outputspinBox.setGeometry(QtCore.QRect(300, 400, 91, 41))
        self.outputspinBox.setObjectName("outputspinBox")
        self.inputlabel = QtWidgets.QLabel(setConfig)
        self.inputlabel.setGeometry(QtCore.QRect(140, 320, 121, 41))
        self.inputlabel.setObjectName("inputlabel")
        self.outputlabel = QtWidgets.QLabel(setConfig)
        self.outputlabel.setGeometry(QtCore.QRect(140, 400, 121, 41))
        self.outputlabel.setObjectName("outputlabel")
        self.curdatelabel = QtWidgets.QLabel(setConfig)
        self.curdatelabel.setGeometry(QtCore.QRect(140, 240, 121, 41))
        self.curdatelabel.setObjectName("curdatelabel")
        self.curdateEdit = QtWidgets.QDateTimeEdit(setConfig)
        self.curdateEdit.setGeometry(QtCore.QRect(300, 240, 141, 41))
        self.curdateEdit.setObjectName("curdateEdit")

        self.retranslateUi(setConfig)
        QtCore.QMetaObject.connectSlotsByName(setConfig)

    def retranslateUi(self, setConfig):
        _translate = QtCore.QCoreApplication.translate
        setConfig.setWindowTitle(_translate("setConfig", "Dialog"))
        self.outputdirButton.setText(_translate("setConfig", "选择输出文件路径"))
        self.inputdirButton.setText(_translate("setConfig", "选择输入文件路径"))
        self.okButton.setText(_translate("setConfig", "确定"))
        self.cancelButton.setText(_translate("setConfig", "取消"))
        self.inputlabel.setText(_translate("setConfig", "输入小时数(范围1-24)"))
        self.outputlabel.setText(_translate("setConfig", "输出小时数(范围1-72)"))
        self.curdatelabel.setText(_translate("setConfig", "设置开始时间"))
